apiVersion: apps/v1
kind: Deployment
metadata:
  name: complete-prodcution-e2e-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: complete-prodcution-e2e-app
  template:
    metadata:
      labels:
        app: complete-prodcution-e2e-app
    spec:
      containers:
        - name: complete-prodcution-e2e-app
          image: lugentil/complete-prodcution-e2e-pipeline:1.0.0-68
          resouces:
            limits:
              memory: "256Mi"
              cpu: "500m"
            ports:
              - containerPort: 8080